### ISSUE TITLE
eXist-db releases moved to github

### ISSUE THREAD

**Issue by bwbohl** [peterstadler/existdb-docker#1]
eXist db is no longer available through bintray, release are now being published through github. The Dockerfile has to be changed accordingly.

**Comment by peterstadler** [comment]
Hi @bwbohl, are you going to send in a PR from your commit 86631a95e53ab43edc0f26dd969645bb1be414d4 (against the 5.2 branch)?
That would be much appreciated  :)

**Comment by bwbohl** [comment]
sorry, too late :-/
