### ISSUE TITLE
Plattform-specific builds

### ISSUE THREAD

**Issue by bwbohl** [peterstadler/existdb-docker#4]
It would be great if there were platform-specific builds of this dockerfile, especially for linux/arm64v8

**Comment by peterstadler** [comment]
I think this works now (`linux/arm64` and `linux/amd64` being supported), so closing the issue for now.

`linux/arm/v7` is a little bit trickier since our openjdk base image does not support it. We would need to switch to e.g. `eclipse-temurin` for this. We might do that if there's demand?!
