### ISSUE TITLE
exist-db v6.0.1 released

### ISSUE THREAD

**Issue by bwbohl** [peterstadler/existdb-docker#5]
A new version of eXist-db has been released that should be used as default version.

**Comment by peterstadler** [comment]
The GitHub actions already use the 6.0.1 version:
https://github.com/peterstadler/existdb-docker/blob/8c23812a87b4cab6cd9b26ed50bb0900da1e967e/.github/workflows/docker-publish.yml#L33

But it should also be updated in the Dockerfile. Will do!
